{{- if empty .Values.manualSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: fastapi-apps
type: Opaque
data:
  KEY_VAULT_NAME: {{ .Values.REDIS_HOST | b64enc }}
  REDIS_PORT: {{ .Values.REDIS_PORT | b64enc }}
  REDIS_PWD: {{ .Values.REDIS_PWD | b64enc }}
  BLOB_ACCOUNT_NAME: {{ .Values.BLOB_ACCOUNT_NAME | b64enc }}
  SQL_URL: {{ .Values.SQL_URL | b64enc }}
  BLOB_CON_STR: {{ .Values.BLOB_CON_STR | b64enc }}